# Вторая лабораторная работа
**Выполнил:** Хрипков Тимофей, группа ИУ5-65Б

Обработка пропусков в данных, кодирование категориальных признаков и масштабирование

In [ ]:
!pip install scikit-learn pandas numpy seaborn matplotlib

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Я буду использовать готовый датасет Palmer Penguins

In [ ]:
df = sns.load_dataset('penguins')

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [ ]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

Строки с пропусками в колонке `sex` можно удалить, так как их немного.

In [ ]:
clear = df.dropna(subset=['sex'])
clear.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

Числовые признаки с пропусками мы заменим на медианные значения.

In [ ]:
clear['bill_length_mm'] = clear['bill_length_mm'].fillna(clear['bill_length_mm'].median())
clear['bill_depth_mm'] = clear['bill_depth_mm'].fillna(clear['bill_depth_mm'].median())
clear['flipper_length_mm'] = clear['flipper_length_mm'].fillna(clear['flipper_length_mm'].median())
clear['body_mass_g'] = clear['body_mass_g'].fillna(clear['body_mass_g'].median())
clear.isnull().sum()

/tmp/ipykernel_15667/292434381.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['bill_length_mm'] = clear['bill_length_mm'].fillna(clear['bill_length_mm'].median())
/tmp/ipykernel_15667/292434381.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['bill_depth_mm'] = clear['bill_depth_mm'].fillna(clear['bill_depth_mm'].median())
/tmp/ipykernel_15667/292434381.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['flipper_length_mm'] = clear['flipper_length_mm'].fillna(clear['flipper_length_mm'].median())
/tmp/ipykernel_15667/292434381.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['body_mass_g'] = clear['body_mass_g'].fillna(clear['body_mass_g'].median())

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

От пропусков избавились. Переходим к кодированию категориальных признаков.

In [ ]:
clear.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 20.8+ KB

Закодируем пол как 0 и 1.

In [ ]:
clear['sex'] = clear['sex'].map({'Male': 0, 'Female': 1})
clear.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    int64
dtypes: float64(4), int64(1), object(2)
memory usage: 20.8+ KB

/tmp/ipykernel_15667/2822204845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['sex'] = clear['sex'].map({'Male': 0, 'Female': 1})

Вид пингвина (`species`) мы закодируем от 1 до 3, так как его можно упорядочить.

In [ ]:
clear['species'] = clear['species'].map({'Adelie': 1, 'Chinstrap': 2, 'Gentoo': 3}).astype(int)
clear.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    int64
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    int64
dtypes: float64(4), int64(2), object(1)
memory usage: 20.8+ KB

/tmp/ipykernel_15667/1661154352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clear['species'] = clear['species'].map({'Adelie': 1, 'Chinstrap': 2, 'Gentoo': 3}).astype(int)

Закодируем one-hot колонку `island`

In [ ]:
island_dummies = pd.get_dummies(clear['island'], prefix='island')
island_dummies = island_dummies.astype(int)
clear = pd.concat([clear, island_dummies], axis=1)
clear = clear.drop('island', axis=1)
clear.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    int64
 1   bill_length_mm     333 non-null    float64
 2   bill_depth_mm      333 non-null    float64
 3   flipper_length_mm  333 non-null    float64
 4   body_mass_g        333 non-null    float64
 5   sex                333 non-null    int64
 6   island_Biscoe      333 non-null    int64
 7   island_Dream       333 non-null    int64
 8   island_Torgersen   333 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 26.0 KB

Масштабируем данные.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Масштабируем все признаки, кроме целевого `species`
clear_scaled = pd.DataFrame(scaler.fit_transform(clear.drop('species', axis=1)))

clear_scaled.describe()

,0,1,2,3,4,5,6,7
count,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000
mean,0.432465,0.483912,0.490966,0.418627,0.495495,0.489489,0.369369,0.141141
std,0.198861,0.234433,0.237555,0.223671,0.500732,0.500642,0.483360,0.348691
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.269091,0.297619,0.305085,0.236111,0.000000,0.000000,0.000000,0.000000
50%,0.450909,0.500000,0.423729,0.375000,0.000000,0.000000,0.000000,0.000000
75%,0.600000,0.666667,0.694915,0.576389,1.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000